# Generated by Django 3.1.7 on 2021-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210523_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneteam_model',
            name='画像',
        ),
    ]
